[project]
name = "teleimager"
version = "1.5.0"
description = "TeleImager: multi-camera image streaming service for unitree teleoperation"
authors = [
    { name = "silencht", email = "silencht@qq.com" }
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.9,<3.11"
dependencies = [
    "logging_mp",
    "opencv-python",
    "numpy>=1.21",
    "pyyaml",
    "pyzmq",
    "psutil>=7.2.1",
    "opencv-python-headless",
    "pyopengl",
    "requests",
    "pip",
    "simplejpeg>=1.7.3",
]
[project.optional-dependencies]
# execute pip install -e ".[server]" to install server dependencies
server = [
    "aiohttp",
    "aiortc",
    # "pupil-labs-uvc",
]

[project.urls]
Homepage = "https://github.com/unitreerobotics/teleimager"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv.sources]
pupil-labs-uvc = { git = "https://github.com/pupil-labs/pyuvc.git", rev = "master" }

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
teleimager-server = "teleimager.image_server:main"
teleimager-client = "teleimager.image_client:main"

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64"]

[tool.pixi.pypi-dependencies]
teleimager = { path = ".", editable = true, extras = ["server"] }

[tool.pixi.dependencies]
librealsense = ">=2.56.5,<3"

[tool.pixi.tasks]
# install_zed = "pip install --no-deps ./pyzed-5.1-cp310-cp310-linux_aarch64.whl"
install_zed = "python /usr/local/zed/get_python_api.py"
